### ISSUE TITLE
goreturns: Install seems to be down

### ISSUE THREAD

**Issue by Makman2** [sqs/goreturns#21]
Hi :)

Your link sourcegraph.com/sqs/goreturns looks like being down. Also you seem to use `gcimporter` as a dependency, but it was moved to another page:

```
+ go get -u sourcegraph.com/sqs/goreturns
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
	/usr/local/go/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
	/home/ubuntu/.go_workspace/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
	/usr/local/go_workspace/src/golang.org/x/tools/go/gcimporter
package golang.org/x/tools/go/types: no buildable Go source files in /home/ubuntu/.go_workspace/src/golang.org/x/tools/go/types
```
Taken from our build-log here: https://circleci.com/gh/coala-analyzer/coala-bears/975

It would be nice if you could fix that as soon as possible, we from coala rely on your cool tool in our testing step :)

**Comment by Makman2** [comment]
Oh forgot to write that I think the new gcimporter is here: https://godoc.org/golang.org/x/tools/go/gcimporter15

**Comment by sils1297** [comment]
@Makman2 there's no way we can workaround this? I don't know pulling the gcimporter from somewhere else installing it manually on the CI so we can work again on that repo?

**Comment by sqs** [comment]
Thanks for the report. Are you able to submit a PR? I will merge asap.

**Comment by shurcooL** [comment]
Isn't this a duplicate of #19, which was already fixed in #20?

@Makman2, your CI failure is a day old. Try restarting it, the issue should be fixed by now.

**Comment by Makman2** [comment]
Yes it works again, thank you and sorry for bothering :3

**Comment by GoodGun** [comment]
install seems to be down right now...
