### ISSUE TITLE
Install doesn't work

### ISSUE THREAD

**Issue by knadh** [sqs/goreturns#23]
`go version go1.6.2 linux/amd64`

```
$ go get github.com/sqs/goreturns
package sourcegraph.com/sqs/goreturns/returns: unrecognized import path "sourcegraph.com/sqs/goreturns/returns" (parse https://sourcegraph.com/sqs/goreturns/returns?go-get=1: no go-import meta tags)
```

The entire `https://sourcegraph.com/sqs*` tree returns a 404.

PS: Looks like it's the same issue as https://github.com/sqs/goreturns/issues/21, but unable to figure out how the fix works

**Comment by sqs** [comment]
This could be an ephemeral network failure. Do you see this output?

```
$ curl 'https://sourcegraph.com/sqs/goreturns/returns?go-get=1'
<html><head><meta name="go-import" content="sourcegraph.com/sqs/goreturns git https://github.com/sqs/goreturns"></head><body></body></html>
```

If so, please try running the `go get` command again.

**Comment by knadh** [comment]
@sqs Ha, Cloudflare's captcha that just doesn't go away.

I cloned the library and changed the import from sourcegraph to the github.com repo to make it work.

**Comment by the-shank** [comment]
@knadh thanks for the solution, I was going crazy with the capcha!

**Comment by alwindoss** [comment]
Do `go get -u -v github.com/sqs/goreturns` this should work
