### ISSUE TITLE
Struct and bson tags alignment issues

### ISSUE THREAD

**Issue by carlca** [sqs/goreturns#39]
I don't know if I should be addressing this issue to you or @bradfitz or someone else. Anyhow:

When I save my go code, my structs are being aligned like this:
![screen shot 2017-11-24 at 15 18 20](https://user-images.githubusercontent.com/260612/33216230-e24b034e-d12a-11e7-9fec-f6d960a262f7.png)

I would prefer the automatic alignment of the `string bson` info to carry on over the comments, like so:
![screen shot 2017-11-24 at 15 23 04](https://user-images.githubusercontent.com/260612/33216365-75d4cba4-d12b-11e7-92a0-98084a49e600.png)

Is there any way of achieving this with `goreturns`, `goimports` or `gofmt`? Thanks!

**Comment by sqs** [comment]
This would be a decision for gofmt. However, it’s unlikely they would change it or make it configurable since it would result in a lot of unexpected diffs.

**Comment by carlca** [comment]
I take your point. After all, this is a tool that is intended to cut down the variation in formatting, *not* result in a lot of unexpected diffs!
